#!/bin/bash

echo "Testing /view and /edit commands in parsql CLI"
echo ""
echo "Navigate to test directory:"
echo "  cd /home/burak/kaynak/projeler/parsql-libs/parsql/test-cli-migrations"
echo "  ../target/release/parsql"
echo ""
echo "Test commands:"
echo "  /connect sqlite:test.db"
echo "  /status"
echo "  /view 20250101000000"
echo "  /view 20250101000000 down"
echo "  /view 20250102000000"
echo "  /edit 20250101000000"
echo ""
echo "In /view mode:"
echo "  - Use arrow keys or j/k to scroll"
echo "  - PgUp/PgDn for page scroll"
echo "  - q or Esc to close"
echo ""
echo "The /edit command will open the file in your \$EDITOR (default: vi)"